spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alexandreiev/SpringInActionTacoCloud
          default-label: ch13
          search-paths: microservices/configs
server:
  port: 8888
