server:
  port: 9090
  ssl:
    key-store: classpath:mykeys.jks
    key-store-password: 123456
    key-password: 123456

greeting:
  welcome: You are using ${spring.application.name}.

spring:
  datasource:
#    url: jdbc:mysql://localhost/tacocloud
    url: jdbc:h2:mem:testdb
#    username: tacodb
#    password: tacopassword
#    driver-class-name: com.mysql.jdbc.Driver
#    initialize: true
    initialization-mode: always
    schema:
      - classpath:schema.sql
#      - order-schema.sql
#      - ingredient-schema.sql
#      - taco-schema.sql
#      - user-schema.sql
    data:
      - classpath:data.sql
#      - ingredients.sql
#    jndi-name: java:/comp/env/jdbc/tacoCloudDs

  jpa:
    hibernate:
      ddl-auto: update

logging:
#  path: /var/logs/
#  file: TacoCloud.log  // rotation once reach 10Mb by default
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG