eureka:
  client:
#    fetch-registry: false
#    register-with-eureka: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://${other.eureka.host}:${other.eureka.port}/eureka
#  server:
#    enable-self-preservation: false

---


spring:
  config:
    activate:
      on-profile: eureka-1
#  profiles: eureka
  application:
    name: eureka-1

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
#other:
#  eureka:
#    host: localhost
#    port: 8762

---
spring:
  config:
    activate:
      on-profile: eureka-2
#  profiles: eureka-2
  application:
    name: eureka-2

server:
  port: 8762

eureka:
  instance:
    hostname: localhost
other:
  eureka:
    host: localhost
    port: 8761
