server:
  port: 9090
taco:
  orders:
    pageSize: 10

spring:
  datasource:
    url: jdbc:h2:mem:testdb;database_to_lower=true


logging:
#  path: /var/logs/
#  file: TacoCloud.log  // rotation once reach 10Mb by default
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG